name: m3u8_download
description: A m3u8 download, support linux, mac and windows, dependency on ffmpeg.
version: 1.5.1
repository: https://github.com/CaiJingLong/m3u8_download

environment:
  sdk: ">=2.19.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dext: ^0.1.2
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables: 
  m3u8: m3u8_download