name: Upgrade version

on:
  push:
    branches:
      - main

jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送提交
      id-token: write  # 启用OIDC身份验证
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用官方Token认证
          fetch-depth: 0  # 获取完整提交历史

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Upgrade version
        run: dart run scripts/upgrade_version.dart

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        env:
          COMMITTER_NAME: github-actions[bot]
          COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          # 配置本地Git用户信息
          git config --local user.name "$COMMITTER_NAME"
          git config --local user.email "$COMMITTER_EMAIL"
          
          # 生成符合规范的提交信息
          git add -u
          git commit -m "chore: automated version upgrade" \
            --author="$COMMITTER_NAME <$COMMITTER_EMAIL>"
          
          # 使用安全方式推送变更
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:main
