name: Upgrade version

on:
  push:
    branches:
      - main

jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Upgrade version
        run: dart run scripts/upgrade_version.dart
      - name: Check have change
        id: check-commit
        run: |
          git_status=$(git status --porcelain)
          if [ -n "$git_status" ]; then
            echo "There are uncommitted changes."
            echo "HAS_CHANGES=true" >> $GITHUB_ENV  # Set has_changes output to true
          else
            echo "No uncommitted changes."
            echo "HAS_CHANGES=false" >> $GITHUB_ENV  # Set has_changes output to false
          fi
      - name: Setup gh to push commit
        run: |
          if [ $HAS_CHANGES = "false" ]; then
            echo "No uncommitted changes."
            exit 0
          fi
          gh auth setup-git -h github.com
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: upgrade version" --signoff
          git push